### ISSUE TITLE
Generic type 'ɵɵFactoryDef' requires 1 type argument(s).

### ISSUE THREAD

**Issue by Dwigth** [ismetkizgin/ng-search-filter#1]
I just added this package to my project and after reload the ng serve process everything works fine, but the console is showing the next error:
![image](https://user-images.githubusercontent.com/20452841/109864358-5914bf00-7c28-11eb-8225-128d3a116717.png)

This is the output of my angular version:
![image](https://user-images.githubusercontent.com/20452841/109863922-d7249600-7c27-11eb-9c8e-5996583ae173.png)

It should be clarified that the filter works as is intended, but in the html the error continues:
![image](https://user-images.githubusercontent.com/20452841/109864957-199aa280-7c29-11eb-92a2-2874bab80253.png)

Any suggestion of what might be wrong?

Thanks in advance.

**Comment by ismetkizgin** [comment]
The ng-search-filter package supports 10.0 and its top versions.
